
#include <stdio.h>
#include <assert.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>

#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

#include "rgba_to_rgb.h"

// From 'man encodedv' on 24-May-2009, latest CVS version.

/*
       -i, --input=filter-name
              Choose input-filter: [>ppm<, pgm, video] The ppm-filter only supports raw rgb ppm files.  The pgm file format is the one generated by mpeg2dec of the livid project. ( http://linuxvideo.org ) This means: Y-data appended by U and V data which are  scaled  down
              by 2 and placed side by side. This option defaults to PPM. Some things you want to keep in mind:

*/

int rgba2ppm(int rgba_fd, int out_fd, int xres, int yres) {

  int depth = 256;

  unsigned char *rgba_line;

  unsigned char *rgb_line;

  char image_header[80];

  int image_header_len;

  int read_bytes;

  int write_bytes;

  int retval;

  assert(rgba_fd >= 0 && out_fd >= 0 && xres > 0 && yres > 0);

  rgba_line = malloc(xres*4*2);
  rgb_line = malloc(xres*3);

  if (rgb_line==NULL || rgba_line==NULL) {
    
    free(rgb_line);
    free(rgba_line);

    return -1;

  }

  retval = sprintf(image_header, "P6\n%d %d 256\n", xres, yres, depth);
  if (retval <= 0 || retval > sizeof(image_header)) {
    fprintf(stderr, "%s: Trouble generating image header.\n", __FUNCTION__, retval);
    return -1;
  }

  image_header_len = strlen(image_header);

  retval = write(out_fd, image_header, image_header_len);
  if (retval != image_header_len) {
    fprintf(stderr, "%s: Trouble writing image_header to out_fd=%d. Expected %d but got %d.\n", __FUNCTION__, out_fd, image_header_len, retval);
    return -1;
  }

  for ( ; yres > 0; yres--) {

    read_bytes = read(rgba_fd, rgba_line, xres*8);
    if (read_bytes!=xres*8) {
      fprintf(stderr, "%s: Trouble reading from rgba_fd=%d. Expected %d but got %d\n", __FUNCTION__, rgba_fd, xres*8, read_bytes);
      return -1;
    }

    rgba_to_rgb(rgba_line, rgb_line, xres);

    write_bytes = write(out_fd, rgb_line, xres*3);
    if (write_bytes!=xres*3) {
      fprintf(stderr, "%s: Trouble writing to out_fd=%d. Expected %d but got %d\n", __FUNCTION__, out_fd, xres*3, write_bytes);
      return -1;
    }

  }

  return 0;

}

int main(int argc, char *argv[]) {

  char *input_filename = argc > 1 ? argv[1] : NULL;

  int input_xres = argc > 2 ? strtol(argv[2], NULL, 10) : 0;

  int input_yres = argc > 3 ? strtol(argv[3], NULL, 10) : 0;

  int retval;

  int rgba_fd;

  int write_fd = 1;

  if (!input_xres || !input_yres) {

    printf("%s: Usage: input_filename xres yres\n", __FUNCTION__);

    return -1;

  }

  printf("%s: Using %dx%d.\n", __FUNCTION__, input_xres, input_yres);

  assert(input_filename!=NULL);

  rgba_fd = open(input_filename, O_RDONLY);
  if (rgba_fd==-1) {
    fprintf(stderr, "%s: Trouble opening .rgba file=%s\n", __FUNCTION__, input_filename);
    return -1;
  }

  retval = rgba2ppm(rgba_fd, write_fd, input_xres, input_yres);
  if (retval != 0) {
    printf("%s: Problem with rgba2ppm.\n", __FUNCTION__);
    return -1;
  }

  retval = close(rgba_fd);
  if (retval==-1) {
    fprintf(stderr, "%s: Trouble closing rgba_fd=%d\n", __FUNCTION__, rgba_fd);
    return -1;
  }

  retval = close(write_fd);
  if (retval==-1) {
    fprintf(stderr, "%s: Trouble closing write_fd=%d\n", __FUNCTION__, write_fd);
    return -1;
  }

  return 0;

}
